#cloud-config
hostname: debian
timezone: Europe/Dublin
users:
- name: root
  groups:
  - sudo
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMC6+ymNKX8VPyFL8MpFCFL61baK9SJ2uSI+rsuYwYdX baskski@gmail.com
  sudo: ALL=(ALL) NOPASSWD:ALL
package_update: true
packages:
- qemu-guest-agent
- haproxy
runcmd:
- systemctl enable qemu-guest-agent
- systemctl start qemu-guest-agent
- |
  cat <<EOF > /etc/haproxy/haproxy.cfg
  defaults k8s
    mode tcp
    timeout connect 10s
    timeout server 30s
    timeout client 30s
  frontend k8s from k8s
    bind :6443
    default_backend k8s
  frontend talos from k8s
    bind :50000
    default_backend talos
  backend k8s from k8s
    server s1 192.168.40.201:6443 check
    server s2 192.168.40.202:6443 check
    server s3 192.168.40.203:6443 check
  backend talos from k8s
    server s1 192.168.40.201:50000 check
    server s2 192.168.40.202:50000 check
    server s3 192.168.40.203:50000 check
  EOF
- systemctl enable haproxy
- systemctl restart haproxy
