apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shelfmark
  namespace: media
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    global:
      createDefaultServiceAccount: false
    controllers:
      shelfmark:
        type: statefulset
        containers:
          shelfmark:
            image:
              repository: ghcr.io/calibrain/shelfmark
              tag: v1.3.2
            env:
              # PGID: "0"
              # PUID: "0"
              TZ: Europe/Dublin
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health
                    port: 8084
            resources:
              requests:
                cpu: 50m
                memory: 300Mi
        statefulset:
          volumeClaimTemplates:
          - name: config
            size: 1Gi
            storageClass: proxmox
            accessMode: ReadWriteOnce
            labels:
              cluster-destroy-delete: "true"
            globalMounts:
            - path: /config
    persistence:
      media:
        type: persistentVolumeClaim
        existingClaim: media
        globalMounts:
        - path: /audiobooks
          subPath: audiobooks
        - path: /books
          subPath: books
        - path: /torrents/audiobooks
          subPath: torrents/audiobooks
        - path: /torrents/books
          subPath: torrents/books
    rawResources:
      scaledObject:
        manifest:
          apiVersion: keda.sh/v1alpha1
          kind: ScaledObject
          metadata:
            name: shelfmark
          spec:
            scaleTargetRef:
              kind: StatefulSet
              name: shelfmark
            triggers:
            - type: cron
              metadata:
                timezone: Europe/Dublin
                start: 10 04 * * *
                end: 50 03 * * *
                desiredReplicas: "1"
    route:
      shelfmark:
        hostnames:
        - shelfmark.cecobask.com
        parentRefs:
        - name: envoy
          namespace: envoy-gateway
        rules:
        - backendRefs:
          - port: 80
          timeouts:
            request: 3h
    service:
      shelfmark:
        controller: shelfmark
        clusterIP: None
        ports:
          http:
            port: 80
            targetPort: 8084
