httpRoute:
  enabled: true
  hostname: audiobookshelf.cecobask.com
image:
  repository: ghcr.io/advplyr/audiobookshelf
  tag: 2.32.1
livenessProbe:
  failureThreshold: 5
  httpGet:
    path: /healthcheck
    port: 13378
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 10
name: audiobookshelf
persistence:
  enabled: true
  capacity: 10Gi
resources:
  requests:
    cpu: 100m
    memory: 500Mi
securityContext: ~
service:
  targetPort: 13378
