apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
helmCharts:
- repo: oci://ghcr.io/openbao/charts
  name: openbao
  version: 0.19.0
  releaseName: openbao
  namespace: openbao
  valuesFile: values.yaml
