env:
- name: ORIGIN
  value: https://profilarr.cecobask.com
httpRoute:
  enabled: true
  hostname: profilarr.cecobask.com
image:
  repository: ghcr.io/dictionarry-hub/profilarr
  tag: 2.0.8
livenessProbe:
  failureThreshold: 5
  httpGet:
    path: /api/v1/health
    port: 6868
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 10
name: profilarr
persistence:
  enabled: true
  capacity: 1Gi
resources:
  requests:
    cpu: 100m
    memory: 100Mi
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
service:
  targetPort: 6868
volumeMounts:
- mountPath: /config
  name: config
volumes: ~
