apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero
resources:
- namespace.yaml
- secret.yaml
helmGlobals:
  chartHome: ../../helm
helmCharts:
- repo: https://vmware-tanzu.github.io/helm-charts
  name: velero
  version: 12.0.2
  releaseName: velero
  namespace: velero
  includeCRDs: true
  valuesFile: values.yaml
- name: velero-schedules
  namespace: velero
  valuesFile: schedules.yaml
