apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: qui
spec:
  schedule: CRON_TZ=Europe/Dublin 00 04 * * *
  template:
    includedNamespaces:
    - media
    includedResources:
    - persistentvolumeclaims
    labelSelector:
      matchLabels:
        app: qui
    snapshotMoveData: true
    snapshotVolumes: true
    storageLocation: backblaze
    ttl: 72h
