apps:
- name: audiobookshelf
  namespace: media
- name: bazarr
  namespace: media
- name: jellyfin
  namespace: media
- name: profilarr
  namespace: media
- name: prowlarr
  namespace: media
- name: qbittorrent
  namespace: media
- name: qui
  namespace: media
- name: radarr
  namespace: media
- name: seerr
  namespace: media
- name: shelfmark
  namespace: media
- name: sonarr
  namespace: media
