apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: credentials
spec:
  refreshInterval: 0s
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: accessKey
    remoteRef:
      key: b7d087ef-58d8-4cec-aaf7-b4630141141b
  - secretKey: keyID
    remoteRef:
      key: fb7fcdc2-5c35-4dd9-ac8e-b463014148ec
  target:
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .keyID }}
          aws_secret_access_key={{ .accessKey }}
