configuration:
  backupStorageLocation:
  - bucket: homelab-5678b8898f
    config:
      region: eu-central-003
      s3Url: https://s3.eu-central-003.backblazeb2.com
    credential:
      key: cloud
      name: credentials
    default: true
    name: backblaze
    prefix: velero
    validationFrequency: 60m
    provider: aws
  features: EnableCSI
credentials:
  existingSecret: credentials
initContainers:
- image: velero/velero-plugin-for-aws:v1.14.1
  name: velero-plugin-for-aws
  volumeMounts:
  - mountPath: /target
    name: plugins
metrics:
  serviceMonitor:
    enabled: true
resources:
  limits: ~
  requests:
    cpu: 200m
    memory: 256Mi
snapshotsEnabled: false
upgradeCRDs: false
