apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    global:
      createDefaultServiceAccount: false
    controllers:
      prowlarr:
        type: statefulset
        containers:
          prowlarr:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: 2.3.6
            env:
              TZ: Europe/Dublin
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 9696
            resources:
              requests:
                cpu: 50m
                memory: 250Mi
        statefulset:
          volumeClaimTemplates:
          - name: config
            size: 1Gi
            storageClass: proxmox
            accessMode: ReadWriteOnce
            labels:
              cluster-destroy-delete: "true"
            globalMounts:
            - path: /config
    rawResources:
      scaledObject:
        manifest:
          apiVersion: keda.sh/v1alpha1
          kind: ScaledObject
          metadata:
            name: prowlarr
          spec:
            scaleTargetRef:
              kind: StatefulSet
              name: prowlarr
            triggers:
            - type: cron
              metadata:
                timezone: Europe/Dublin
                start: 10 04 * * *
                end: 50 03 * * *
                desiredReplicas: "1"
    route:
      prowlarr:
        hostnames:
        - prowlarr.cecobask.com
        parentRefs:
        - name: envoy
          namespace: envoy-gateway
        rules:
        - backendRefs:
          - port: 80
          timeouts:
            request: 30s
    service:
      prowlarr:
        controller: prowlarr
        clusterIP: None
        ports:
          http:
            port: 80
            targetPort: 9696
