apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry
  namespace: opentelemetry
spec:
  chart:
    spec:
      chart: opentelemetry-kube-stack
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      version: 0.20.5
  dependsOn:
  - name: cert-manager
    namespace: cert-manager
  interval: 1h
  values:
    clusterName: homelab
    collectors:
      agent:
        config:
          exporters:
            otlphttp/vlogs:
              logs_endpoint: http://vlsingle-victoria-logs.victoria-metrics.svc.cluster.local:9428/insert/opentelemetry/v1/logs
          processors:
            batch:
              send_batch_size: 10000
          service:
            pipelines:
              logs:
                receivers:
                - file_log
                processors:
                - k8s_attributes
                - batch
                exporters:
                - otlphttp/vlogs
        enabled: true
        fullnameOverride: opentelemetry-agent
        mode: daemonset
        presets:
          kubernetesAttributes:
            enabled: true
          logsCollection:
            enabled: true
      daemon:
        enabled: false
    crds:
      installPrometheus: false
    opentelemetry-operator:
      admissionWebhooks:
        certManager:
          issuerRef:
            name: internal-ca
            kind: ClusterIssuer
      fullnameOverride: opentelemetry-operator
