apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      version: v1.2.1
  interval: 1h
  values:
    bitwarden-sdk-server:
      enabled: true
      image:
        tls:
          secretName: bitwarden-sdk-server
      resources:
        requests:
          cpu: 10m
          memory: 30Mi
    installCRDs: false
    resources:
      requests:
        cpu: 10m
        memory: 150Mi
    webhook:
      certManager:
        cert:
          issuerRef:
            kind: ClusterIssuer
            name: internal-ca
        enabled: true
      lookaheadInterval: 48h
      resources:
        requests:
          cpu: 10m
          memory: 200Mi
