apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-core
  namespace: flux-system
spec:
  interval: 10m
  path: kubernetes/infra/core
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-apps
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-core
    namespace: flux-system
  interval: 10m
  path: kubernetes/infra/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
