apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  chartRef:
    kind: OCIRepository
    name: node-feature-discovery
  interval: 1h
  values:
    gc:
      resources:
        limits: ~
        requests:
          cpu: 10m
          memory: 50Mi
    master:
      resources:
        limits: ~
        requests:
          cpu: 10m
          memory: 50Mi
    worker:
      resources:
        limits: ~
        requests:
          cpu: 10m
          memory: 100Mi
