apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-secrets-webhook
spec:
  secretName: external-secrets-webhook
  dnsNames:
  - external-secrets-webhook
  - external-secrets-webhook.external-secrets
  - external-secrets-webhook.external-secrets.svc
  - external-secrets-webhook.external-secrets.svc.cluster.local
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  duration: 8760h
