apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-secrets-webhook
spec:
  commonName: cert-manager-external-secrets-webhook-tls
  isCA: true
  secretName: external-secrets-webhook-tls
  subject:
    organizations:
    - external-secrets.io
  dnsNames:
  - external-secrets-webhook.external-secrets.svc.cluster.local
  - localhost
  ipAddresses:
  - 127.0.0.1
  - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: self-signed
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: external-secrets-webhook
spec:
  ca:
    secretName: external-secrets-webhook-tls
