{{- range .Values.apps }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ .name }}
spec:
  schedule: CRON_TZ=Europe/Dublin 00 04 * * *
  template:
    includedNamespaces:
    - {{ .namespace }}
    includedResources:
    - persistentvolumeclaims
    labelSelector:
      matchLabels:
        app: {{ .name }}
    snapshotMoveData: true
    snapshotVolumes: true
    storageLocation: backblaze
    ttl: 72h
---
{{- end }}
