- Torrents:
  - Aither:
    - href: https://aither.cc
      abbr: AIT
  - Anthelion:
    - href: https://anthelion.me
      abbr: ANT
  - Bayflix:
    - href: https://bayflix.is
      abbr: BF
  - Blutopia:
    - href: https://blutopia.cc
      abbr: BLU
  - MyAnonaMouse:
    - href: https://myanonamouse.net
      abbr: MAM
  - TorrentLeech:
    - href: https://torrentleech.org
      abbr: TL
- Bookmarks:
  - Backblaze:
    - description: S3 cloud storage
      href: https://backblaze.com
      icon: backblaze
  - Bitwarden:
    - description: Password and secret manager
      href: https://vault.bitwarden.com
      icon: bitwarden
  - Homelab:
    - description: Source code on GitHub
      href: https://github.com/cecobask/homelab
      icon: github-light
  - Portfolio:
    - description: Portfolio website
      href: https://cecobask.com
      icon: mdi-console
